//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_Ratings
    {
        public int id { get; set; }
        public int book_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> user_id { get; set; }
        public string comment { get; set; }
        public string timestamp { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Books Books { get; set; }
    }
}
