//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> username_id { get; set; }
        public string reserved_date { get; set; }
        public string return_date { get; set; }
        public Nullable<bool> check_in { get; set; }
        public Nullable<bool> check_out { get; set; }
        public Nullable<int> renewTimes { get; set; }
        public Nullable<int> library_id { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Libraries Libraries { get; set; }
        public virtual Users Users { get; set; }
    }
}
